import RecommendationsComponent from "../Components/RecommendationsComponent"
import { Lightbulb } from "lucide-react"

const Recommendations = () => {
    return (
        <div className="space-y-8 animate-in fade-in duration-700">
            <div>
                <h1 className="text-3xl font-bold text-gray-900 dark:text-slate-50 tracking-tight flex items-center gap-3">
                    <Lightbulb className="text-amber-500" />
                    Strategic Recommendations
                </h1>
                <p className="text-gray-500 dark:text-slate-400 mt-1">Actionable steps generated by AI to optimize your financial performance.</p>
            </div>

            <div className="max-w-4xl">
                <RecommendationsComponent />
            </div>
        </div>
    )
}

export default Recommendations
